# Studiedesign


I denne oppgaven skal vil jeg ta for meg styrketrening, og forskjellen på et og tre sett på utrente personer. På kryss av alle artiklene gjennomførte de mellom 4-20 repetisjoner per sett. Det spesifikke spørsmålet for er om det vil være en forskjell i forbedring av muskelkraft og muskelvekst. I artiklene jeg har lest er det litt forskjellig valg av spørsmål og hypoteser. I Rhea sin artikkel er det et spørsmål, mens i de andre artiklene er det hypoteser blir svart på. Det spesifikke spørsmålet Rhea har er om det er en forskjell i styrke økning om man gjennomfører et eller tre sett styrketrening (Rhea et al., 2002, s. 525–529). 
Den røde tråden forskerne har finner vi igjen i introduksjonen. Der har forskerne lagt frem andre studier som bygger opp under spørsmålet eller hypotesen det har kommet med. Kryger og Andersen skriver at de forsker på temaet, fordi de har sett i artiklene det har lest at eldre mister muskelkraft og muskelstyrke (Kryger, A. I., & Andersen, J. L. (2007).  Dette bygger oppunder det Galvao og Taffe skriver om hvor de har undersøkt forskjellen i et og tre sett. Dette er helsefremmende forskning for å sørge for at eldre personer kan gjennomføre dagligdagse oppgaver (Galvao, D. A., & Taaffe, D. R. (2005). Rønnestad, Galvao og Taaffe og Rhea forsker på forskjellen mellom et og tre sett hvor utmattelsen i begge sett er maks (Rønnestad et al., 2007, s. 157-163; Galvao, D. A., & Taaffe, D. R. (2005); Rhea et al., 2002, s. 525–529).  
Randomiserte studier er studier hvor intervensjonsgrupper er tilfeldig fordelt, dette vil gi en overføringsverdi til hvordan den faktiske tilstanden i verden der (Hulley, S. B. (2013). Et problem til slike studier kan man tenke seg er personer som melder seg som deltakere. Det kan tenkes at personer som i utgangspunktet er aktive eller har en interesse for trening vil melde seg som deltakere istedenfor personer som kanskje en studie heller vil generalisere svarene sine til. Dette har for eksempel studiene til (Rønnestad et al., 2007, s. 157-163; Rhea et al., 2002, s. 525–529; Kryger, A. I., & Andersen, J. L. (2007); Walker et al., 2017; Rhea et al., 2002, s. 525–529) tatt hensyn til og lagd et skriv om kvalifikasjoner som må bli møtt for å kunne delta i studien.  Antallet i hver gruppe vil kunne føre til en skjevhet i hver gruppe som skal forskes på, derfor vil det være lurt å bruke et randomisert studiedesign. Utvalget i studiene er sprett hvor det skiller 79 år fra yngste person i Rhea sin studie til del eldste personen i Kryger og Andersen sin studie (Rhea et al., 2002, s. 525–529; Kryger, A. I., & Andersen, J. L. 2007). Dette har sine styrker og svakheter hvor man ikke kan knytte alle resultatene til en gitt aldersgruppe, men den positive siden er det er mulig gitt resultatene er like å gi en generell konklusjon hvor alder ikke har en påvirkning på resultatene. 
Størrelsesutvalget til studiene vil være betydelig for hvordan man skal tolke et resultat. Et for lite utvalg vil gi for lite ønske data mens for mye vil gi for utydelig data. Dette er en viktig balansegang for forskere, det avhenger av hvem studien skal generaliseres til og ressurser. Størrelsesutvalget er det en spredning på 90 personer, med Rhea med 18 personer og Walker med 108 personer (Walker et al., 2017; Rhea et al., 2002, s. 525–529). Populasjonen som er med i studiene er kategorisert som lite/utrent eller i en dårligere helsemessig stand enn det. Metoden som er brukt for å rekruttere forsøkspersoner er litt forskjellig fra studie til studie. Walker er det definitivt flest personer med, dette kan ha noe med antall personer som ble spurt og målgruppen som bel forsket på. Walker sin metode for å rekreere personer var veldig bra og omfattende (Walker et al., 2017). Først sendte Walker ut et annonsebrev til 2000 personer innenfor målgruppen i sin kommune (Walker et al., 2017). Walker gikk 454 svar på sine annonsebrev der de svarte på en rekke spørsmål om sin egen helse, fysisk tilstand og andre nyttige opplysninger (Walker et al., 2017). Etter dette spørreskjema ble det plukket ut 148 som fikk være med på en detaljert informasjon prosjektet (Walker et al., 2017). Når prosjektet startet var de nede i 106 personer som gjennomførte intervensjonen (Walker et al., 2017). Galvao og Taaffe hadde en annonse i en avis, det rekrutterte 22 eldre personer Galvao, D. A., & Taaffe, D. R. (2005). I Rønnestad, Kryger og Andersen og Rhea lyktes jeg ikke å finne en spesiell metode for å finne ut hvordan de hadde rekruttert personer (Rønnestad et al., 2007, s. 157-163; Rhea et al., 2002, s. 525–529; Kryger og Andersen).
En positiv tilnærming Walker har er størrelses utvalg er mengden data som kan generaliseres til gruppen han forsker på. Dette vil ha en større i Rønnestads tilfelle som har et mindre utvalg av deltakere vil det kunne ha en negativ effekt, hvor resultatene må tolkes nøyere og man kan stille seg mere kritisk til. På en annen side kan det tenkes at utvalget Walkers utvalg kan inneholde flere feilkilder og bli gjort med lavere kvalitet med tanke på antall deltaker, der Rønnestad har færre deltakere hvor kvaliteten på arbeidet vil kunne være gjort bedre med tanke på tid og ressurser. 
Kryger og andersen gjennomførte biosi, isometrisk daynamometer (30, 60, 120, and 180°/s), Immuncytokjemi og ATPase-histokjemi, fibertypevekst, tverskitt av muskel, SDS-PAGE protein størrelse til å måle og få ut resultater (Kryger, A. I., & Andersen, J. L. (2007). Rønnestad brukte isokjenetisk kneefleksjon og ekstensjon i REV9000 4 oppvarmingsrepitisjoner og 3 gjeldene repetisjoner med hvor den høyeste verdien på forsøket gjelte, 1RM (beinpress, leg ekstensjon, leg curl, sittende brystpress, sittende roing, latisimus nedtrekk, bisepscurl og skulderpress. Oppvarmimng på 40, 75 og 85%. det første forsøket på 1RM var på 5% mindre enn hva 1RM var forutsett. Det beste av 2 forsøk i pre og post test ble brukt i dataen), ultralyd og dexa til å måle og få ut resultater (Rønnestad et al., 2007, s. 157-163). Galvao og Taaffe brukte 1RM ((beinpress, (knefleksjon, kneekstensjon – også i typ humac), biceps curl, triceps ekstensjon, sittende roing og dynamisk isometrisk brystpress. Rhea brukte pre, mid og post tester i Benkpress og beinpress (Rhea et al., 2002, s. 525–529). Walker brukte dynamisk beinpress, Isometrisk kneforlengelse og plantarfleksjonsstyrke, Total kroppssammensetning, ultralyd og aktivitetsnivå (Walker et al., 2017).  
De statistiske testene som ble brukt i artiklene er:
I de forskjellige studiene ble det brukt forskjellige statistiske tester for å svar på sin hypotese/spørsmål. De forskjellige testene vil gi andre måter å tolke dataen på. Alle studiene brukte tester som kom frem til en p-verdi, denne var satt til 0.05 og vil fortelle oss om vi skal forkaste nullhypotesen eller ikke (Frøslie. 2023). Rønnestad og Galvao og Taaffe brukte paret og uparet t-tester (Rønnestad et al., 2007, s. 157-163; Galvao, D. A., & Taaffe, D. R. (2005). Dette er tester to grupper opp mot hverandre hvor man får ut ev p-verdi. Forskjellen på en paret- og uparet t-test er at en paret t-test gir deg gjennomsnittet mellom to relevante grupper og en p-verdi mellom gruppene, den blir også brukt til å teste før og etter en undersøkelse. En uparet t-test brukes på uavhengige grupper og vil kunne bli brukt for å sammenligne to grupper innenfor en «pre-test» («T-test i par - MedTekipedia - NTNU Wiki»).
 Galvao & Taaffe og Walker brukte begge en ANCOVA test. Dette er en meget sterk tar høyde for en eller flere kovariante og vil gi en sammenligning oppgitt i gjennomsnitt. Dette vil gi en støtte troverdighet hvor det er mulig å ha en avhengig variabel (Analysis of Covariance. 2023). 
I studien til Rhea blir Tukey's post hoc test brukt. Dette er en analysemetode som oftest blir brukt etter en ANOVA test, og hjelper med å finne forskjellige forskjeller innad i de forskjellige gruppene. 

Rhea brukte Tukey's post hoc test er en etterfølgende analyse etter ANOVA. Den hjelper til å identifisere spesifikke gruppeforskjeller som er signifikante. Dette er nyttig for å unngå feilaktige konklusjoner om hvilke grupper som er forskjellige.
Samlet sett gir alle testene en verdi på endring fra pre-posttest eller en sammenligning mellom gruppene. Testene gir også ut en p-verdi som forteller hvor sannsynlig hypotesen er. P-verdi på 0.05 vil gi en signifikant forskjell mellom gruppene. Dette tilsvarer en sannsynlighet på 95% for. 
På generelt grunnlag kan de konkludere med at styrketrening med et og tre sett, for utrente eldre og i alle aldre vil kunne har en positiv effekt. Det vil gjøre hverdagslige gjøremål enklere som gå opp en trapp eller reise seg fra en stol Kryger, A. I., & Andersen, J. L. (2007). Derfor mener Kryger og Andersen at styrketrening er viktig å få eldre til å drive med, fordi det vil også ha en effekt på samfunnet hvor eldre ikke vil være avhengig av statelig hjelp (Kryger, A. I., & Andersen, J. L. (2007). Kryger og Andersen skriver også at eldre vil ha en naturlig hyperplasi, altså naturlig muskeltap som skylles alder. Dette er uunngåelig, derfor er det viktig å ta med seg det Rønnestad, Galvao & Taffe, Reah, Walker og Kryker og Andersen konkluderer og finner ut, nemlig at tung styrketrening vil føre til økt muskelvekst og muskelstyrke (Rønnestad et al., 2007, s. 157-163; Rhea et al., 2002, s. 525–529; Kryger, A. I., & Andersen, J. L. (2007); Walker et al., 2017; Rhea et al., 2002, s. 525–529) 

Konklusjonen til forskerne er at det ikke vil være en forskjell mellom et eller tre sett styrketrening til maksimal utmattelse Rønnestad et al., 2007, s. 157-163; Rhea et al., 2002, s. 525–529; Kryger, A. I., & Andersen, J. L. (2007); Walker et al., 2017; Rhea et al., 2002, s. 525–529). 




		

Kilder:

1.	Galvao, D. A., & Taaffe, D. R. (2005). Resistance exercise dosage in older adults: Single‐ versus multiset effects on physical performance and body composition. Journal of the American Geriatrics Society, 53(12), 2090–2097. 
2.	Kryger, A. I., & Andersen, J. L. (2007). Resistance training in the oldest old: Consequences for muscle strength, fiber types, fiber size, and MHC isoforms: Consequences for the resistance training in the oldest old. Scandinavian Journal of Medicine & Science in Sports, 17(4), 422–430. https://doi.org/10.1111/j.1600-0838.2006.00575.x 
3.	Hulley, S. B. (2013). Designing clinical research. Philadelphia, Wolters Kluwer/Lippincott Williams & Wilkins.
4.	Rhea, M. R., Alvar, B. A., Ball, S. D., & Burkett, L. N. (2002). Three sets of weight training superior to 1 set with equal intensity for eliciting strength. The Journal of Strength & Conditioning Research, 16(4), 525–529. 
5.	Rønnestad, B. R., Egeland, W., Kvamme, N. H., Refsnes, P. E., Kadi, F., & Raastad, T. (2007). Dissimilar effects of one-and three-set strength training on strength and muscle mass gains in upper and lower body in untrained subjects. The Journal of Strength & Conditioning Research, 21(1), 157-163. 
6.	Walker, S., Haff, G. G., Häkkinen, K., & Newton, R. U. (2017). Moderate-load muscular endurance strength training did not improve peak power or functional capacity in older men and women. Frontiers in Physiology, 8, 1-11. https://doi.org/10.3389/fphys.2017.00743 
7.	«T-test i par - MedTekipedia - NTNU Wiki». Åpnet 15. november 2023. https://www.ntnu.no/wiki/display/medtekipedia/T-test+i+par.
8.	Frøslie, Kathrine Frey. «p-verdi». I Store norske leksikon, 22. august 2023. https://snl.no/p-verdi.
9.	«Analysis of Covariance». I Wikipedia, 21. september 2023. https://en.wikipedia.org/w/index.php?title=Analysis_of_covariance&oldid=1176424029.
10.	

